const $=id=>document.getElementById(id);const visited=new Set();let micStream,micContext,micFrame,micGeneration=0,catsPlayer=null,musicPlaying=false,musicPlayer=null,ytReady=false,rickPlayer=null;
function show(id){document.body.classList.toggle('room-mode',id==='room');document.querySelectorAll('.screen').forEach(x=>x.classList.toggle('active',x.id===id));window.scrollTo({top:0,behavior:'instant'});}
function confetti(){if(matchMedia('(prefers-reduced-motion: reduce)').matches)return;const colors=['#eaa9b8','#d1bc7b','#7c9f8b','#e7ddd3'];for(let i=0;i<75;i++){const el=document.createElement('i');el.className='confetti-piece';el.style.left=Math.random()*100+'%';el.style.background=colors[i%4];el.style.animationDelay=Math.random()*.6+'s';el.style.animationDuration=2.3+Math.random()*1.4+'s';$('confetti').append(el);setTimeout(()=>el.remove(),4500);}}
function mark(name){visited.add(name);$(name).dataset.visited='true';$('progress').textContent=`${visited.size} of 6 surprises opened`;$('last').hidden=visited.size<6;}
function stopMic(){micGeneration++;cancelAnimationFrame(micFrame);micStream?.getTracks().forEach(t=>t.stop());micStream=null;if(micContext){micContext.close().catch(()=>{});micContext=null;}}
function extinguish(){stopMic();$('candles').classList.add('blown');$('micControls').hidden=true;$('next').hidden=false;$('micHint').textContent='Wish received. Happy 22nd, my love. ♡';confetti();}
$('start').onclick=()=>{show('candles');confetti();};$('manual').onclick=extinguish;$('next').onclick=()=>show('room');
$('enableMic').onclick=async()=>{if(micStream)return;const generation=++micGeneration;$('enableMic').disabled=true;$('micHint').textContent='Allow your microphone, then give your candles a good blow.';try{const stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(generation!==micGeneration){stream.getTracks().forEach(t=>t.stop());return;}micStream=stream;micContext=new(window.AudioContext||window.webkitAudioContext)();await micContext.resume();const analyser=micContext.createAnalyser();analyser.fftSize=1024;micContext.createMediaStreamSource(stream).connect(analyser);const samples=new Uint8Array(analyser.fftSize);let baseline=.015,calibration=performance.now(),above=0,last=performance.now();$('micHint').textContent='One quiet second… then blow toward your microphone.';function listen(){if(!micStream)return;analyser.getByteTimeDomainData(samples);const rms=Math.sqrt(samples.reduce((sum,v)=>sum+((v-128)/128)**2,0)/samples.length);const now=performance.now();const dt=Math.min(100,now-last);last=now;if(now-calibration<1100){baseline=baseline*.9+rms*.1;}else{if(now-calibration<1250)$('micHint').textContent='Make your wish and blow!';above=rms>Math.max(.035,baseline*2.5)?above+dt:Math.max(0,above-dt*1.5);if(above>350){extinguish();return;}}micFrame=requestAnimationFrame(listen);}listen();}catch(e){stopMic();$('micHint').textContent='The microphone isn’t available. You can still make a wish and tap below.';}finally{$('enableMic').disabled=false;}};
window.onYouTubeIframeAPIReady=()=>{ytReady=true;};const yt=document.createElement('script');yt.src='https://www.youtube.com/iframe_api';document.head.append(yt);
function updateRecord(){ $('record').setAttribute('aria-pressed',String(musicPlaying));$('record').classList.toggle('playing',musicPlaying);$('recordLabel').textContent=musicPlaying?'Playing ♫ · tap to pause':'A birthday soundtrack';}
function stopMusic(){musicPlaying=false;try{musicPlayer?.pauseVideo();}catch{}updateRecord();}
$('record').onclick=()=>{mark('record');$('musicPanel').hidden=false;if(musicPlayer){musicPlaying=!musicPlaying;musicPlaying?musicPlayer.playVideo():musicPlayer.pauseVideo();updateRecord();return;}if(ytReady&&window.YT){musicPlayer=new YT.Player('musicPlayer',{videoId:'AgFeZr5ptV8',playerVars:{autoplay:1,start:38,playsinline:1,rel:0},events:{onReady:e=>e.target.playVideo(),onStateChange:e=>{musicPlaying=e.data===YT.PlayerState.PLAYING;updateRecord();}}});musicPlaying=true;updateRecord();}else{$('musicPlayer').innerHTML='<iframe title="22 by Taylor Swift" src="https://www.youtube.com/embed/AgFeZr5ptV8?autoplay=1&start=38&playsinline=1" allow="autoplay; encrypted-media" allowfullscreen></iframe>';$('recordLabel').textContent='Tap play below ♫';}};
$('stopMusic').onclick=()=>{stopMusic();if(!musicPlayer)$('musicPlayer').innerHTML='';$('musicPanel').hidden=true;};
function stopChoir(){document.querySelector('.choir').classList.remove('singing');if(catsPlayer){try{catsPlayer.destroy();}catch{}catsPlayer=null;}$('catsVideo').innerHTML='<div id="catsPlayer"></div>';}
function catsSing(){stopChoir();$('catsVideoError').hidden=true;if(ytReady&&window.YT){catsPlayer=new YT.Player('catsPlayer',{videoId:'9ScOGcdWuPM',playerVars:{autoplay:1,start:7,playsinline:1,rel:0},events:{onReady:e=>{if($('catsDialog').open)e.target.playVideo();},onStateChange:e=>document.querySelector('.choir').classList.toggle('singing',e.data===YT.PlayerState.PLAYING),onError:()=>{$('catsVideoError').hidden=false;document.querySelector('.choir').classList.remove('singing');}}});}else{$('catsVideo').innerHTML='<iframe title="Cats singing Happy Birthday" src="https://www.youtube.com/embed/9ScOGcdWuPM?autoplay=1&start=7&playsinline=1&rel=0" allow="autoplay; encrypted-media" allowfullscreen></iframe>';}}
function openDialog(id,name){stopMusic();mark(name);$(id).showModal();$(id).scrollTop=0;}
$('letter').onclick=()=>openDialog('letterDialog','letter');$('cats').onclick=()=>{openDialog('catsDialog','cats');catsSing();};$('replayCats').onclick=catsSing;
let kissTimers=[];function resetKiss(){kissTimers.forEach(clearTimeout);kissTimers=[];const scene=document.querySelector('.kiss-scene');scene.classList.remove('kissing');scene.dataset.pose='0';}function kiss(){resetKiss();const scene=document.querySelector('.kiss-scene');scene.classList.add('kissing');if(matchMedia('(prefers-reduced-motion: reduce)').matches){scene.dataset.pose='2';}else{[[350,'1'],[800,'2'],[4200,'1'],[4600,'0']].forEach(([delay,pose])=>kissTimers.push(setTimeout(()=>scene.dataset.pose=pose,delay)));}$('voice').currentTime=0;$('voice').play().catch(()=>{});}
$('us').onclick=()=>{openDialog('usDialog','us');kiss();};$('replayKiss').onclick=kiss;
document.querySelectorAll('[data-close]').forEach(button=>button.onclick=()=>button.closest('dialog').close());document.querySelectorAll('dialog').forEach(dialog=>{dialog.addEventListener('close',()=>{stopChoir();$('voice').pause();resetKiss();});dialog.addEventListener('click',e=>{const rect=dialog.getBoundingClientRect();if(e.clientX<rect.left||e.clientX>rect.right||e.clientY<rect.top||e.clientY>rect.bottom)dialog.close();});});
$('last').onclick=()=>{stopMusic();stopChoir();$('voice').pause();show('ending');if(rickPlayer){rickPlayer.playVideo();}else if(ytReady&&window.YT){rickPlayer=new YT.Player('rickFrame',{videoId:'dQw4w9WgXcQ',playerVars:{autoplay:1,playsinline:1,rel:0},events:{onReady:e=>e.target.playVideo()}});}else{$('rickPlayer').innerHTML='<iframe title="One last birthday surprise" src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1&playsinline=1" allow="autoplay; encrypted-media" allowfullscreen></iframe>';}};
function pauseRick(){if(rickPlayer&&typeof rickPlayer.pauseVideo==='function')rickPlayer.pauseVideo();else if(!rickPlayer)$('rickPlayer').innerHTML='<div id="rickFrame"></div>';}
$('backRoom').onclick=()=>{pauseRick();show('room');};
$('backStart').onclick=()=>{pauseRick();if(rickPlayer&&typeof rickPlayer.seekTo==='function')rickPlayer.seekTo(0,true);stopMic();stopChoir();$('stopMusic').onclick();resetKiss();$('voice').pause();$('voice').currentTime=0;visited.clear();window.resetWordle?.();window.resetBalloons?.();['record','letter','cats','us','computer','windowView'].forEach(id=>delete $(id).dataset.visited);$('progress').textContent='0 of 6 surprises opened';$('last').hidden=true;$('candles').classList.remove('blown');$('micControls').hidden=false;$('enableMic').disabled=false;$('next').hidden=true;$('micHint').textContent='Blow toward your microphone when you’re ready.';show('intro');confetti();};
window.addEventListener('pagehide',()=>{stopMic();stopChoir();stopMusic();resetKiss();$('voice').pause();});

// Celebrate as soon as the opening appears.
requestAnimationFrame(()=>confetti());
