(() => {
 const answer='LOTUS', ranks={absent:1,present:2,correct:3};
 let guesses=[],current='',finished=false,keyStates={};
 function score(guess,target=answer){const result=Array(5).fill('absent'),remaining={};for(let i=0;i<5;i++){if(guess[i]===target[i])result[i]='correct';else remaining[target[i]]=(remaining[target[i]]||0)+1;}for(let i=0;i<5;i++){if(result[i]!=='correct'&&remaining[guess[i]]>0){result[i]='present';remaining[guess[i]]--;}}return result;}
 function render(){const board=$('wordleBoard');board.replaceChildren();for(let row=0;row<6;row++){const word=guesses[row]?.word||(row===guesses.length?current:'');for(let col=0;col<5;col++){const tile=document.createElement('div');tile.className='wordle-tile';tile.textContent=word[col]||'';if(guesses[row])tile.classList.add(guesses[row].colors[col]);else if(word[col])tile.classList.add('filled');tile.setAttribute('aria-label',`Row ${row+1}, letter ${col+1}: ${word[col]||'empty'}${guesses[row]?', '+guesses[row].colors[col]:''}`);board.append(tile);}}document.querySelectorAll('[data-wordle-key]').forEach(key=>{key.className='wordle-key';if(keyStates[key.dataset.wordleKey])key.classList.add(keyStates[key.dataset.wordleKey]);});$('wordleReplay').hidden=!finished;}
 function input(key){if(finished)return;if(key==='BACKSPACE'){current=current.slice(0,-1);$('wordleMessage').textContent='';}else if(key==='ENTER'){if(current.length!==5){$('wordleMessage').textContent='Not enough letters';return;}if(!WORDLE_WORDS.has(current)){$('wordleMessage').textContent='Not in word list';return;}const colors=score(current);guesses.push({word:current,colors});[...current].forEach((letter,i)=>{if((ranks[colors[i]]||0)>(ranks[keyStates[letter]]||0))keyStates[letter]=colors[i];});finished=current===answer||guesses.length===6;$('wordleMessage').textContent=current===answer?'You got it!':finished?`The word was ${answer}`:'';current='';}else if(/^[A-Z]$/.test(key)&&current.length<5){current+=key;$('wordleMessage').textContent='';}render();}
 [['Q','W','E','R','T','Y','U','I','O','P'],['A','S','D','F','G','H','J','K','L'],['ENTER','Z','X','C','V','B','N','M','BACKSPACE']].forEach(letters=>{const row=document.createElement('div');row.className='wordle-key-row';letters.forEach(letter=>{const key=document.createElement('button');key.type='button';key.dataset.wordleKey=letter;key.textContent=letter==='BACKSPACE'?'⌫':letter;key.setAttribute('aria-label',letter);key.onclick=()=>input(letter);row.append(key);});$('wordleKeyboard').append(row);});
 window.resetWordle=()=>{guesses=[];current='';finished=false;keyStates={};$('wordleMessage').textContent='';render();};
 $('wordleReplay').onclick=window.resetWordle;
 $('computer').onclick=()=>{stopChoir();$('voice').pause();openDialog('wordleDialog','computer');};
 document.addEventListener('keydown',event=>{if(!$('wordleDialog').open||event.ctrlKey||event.metaKey||event.altKey)return;const key=event.key.toUpperCase();if(/^[A-Z]$/.test(key)||key==='ENTER'||key==='BACKSPACE'){event.preventDefault();input(key);}});
 window.resetWordle();
})();
